### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by crqrdotcom** [mikeshimura/goexcel#1]
Hello,

Is there any chance to make it possible to insert images in sheets? If you could give me some guidelines I can write the functionality and submit a PR. I'm just not used to Excel's internal structure.

Thanks in advance!

**Comment by mikeshimura** [comment]
Thank for your offer.

This library is based on github.com/tealeg/xlsx, and it seems that they not support image yet.

I prefer keep this program simple.

Best regards,

Mike Shimura

**Comment by crqrdotcom** [comment]
@mikeshimura thanks for your reply. Indeed github.com/tealeg/xlsx doesn't support images yet nor there's any prevision for supporting it...

Later on I'll give a deep look into it's source and in Excel's structure guidelines to better understand how this feature could be implemented.

Sadly it seems this won't be available anytime soon :disappointed: 

Thank you very much for your time.

Kind regards,
João Cerqueira
